[workspace]
resolver = "2"
members = [
    "model",
    "frontend",
    "backend"
]

[workspace.dependencies]
model = { path = "model" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "1.3.0"
zip = "0.6.4"